"use client";

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import '@vidstack/react/player/styles/default/theme.css';
import '@vidstack/react/player/styles/default/layouts/video.css';
import Sidebar from '@/components/custom-components/sidebar'
import { cn } from '@/lib/utils'
import Navbar from '@/components/custom-components/navbar'
import { SessionProvider } from "next-auth/react"

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={cn(
        inter.className,
        // ' h-[95vh] w-[100vw] overflow-hidden',
        "custom-scrollbar"
      )}>
        <SessionProvider>
          <Navbar />
          <div className='flex h-full'>
            <Sidebar />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
